name: ml4cp
channels: 
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - pillow
  - matplotlib
  - numpy
  - jupyter
  - seaborn
  - pip
  - cpuonly
  - pytorch=1.11.0
  - torchvision=0.12.0
  - pip:
    - cpmpy
    - lightning==1.9
    - charset-normalizer==3.2.0
